### ISSUE TITLE
Crash Reason: image not found

### ISSUE THREAD

**Issue by mauryabip** [Anyline/anyline-ocr-examples-ios#17]
dyld: Library not loaded: /System/Library/Frameworks/CoreNFC.framework/CoreNFC
  Referenced from: /private/var/containers/Bundle/Application/ADB7C50C-1025-40EA-9058-275613167393/AnylineExamples.app/Frameworks/Anyline.framework/Anyline
  Reason: image not found

**Comment by davlhd** [comment]
Hello, 

Whats the Device / iOS Version you are using?
Are you using Pods to install Anyline?
Which Anyline version are you using?

**Comment by philippAnyline** [comment]
Hi @mauryabip, we currently have a known issue with iOS 12.x devices and coreNFC. https://documentation.anyline.com/toc/platforms/ios/known_limitations.html

If this is the case for you: we are working on a hotfix release to get this issue out of the way. 

The hotfix will be released as soon as possible. Please give us feedback if this issue was resolved for you, as soon as the hotfix is out, thanks! :)

**Comment by mauryabip** [comment]
@philippAnyline 

We are able to run now. Thanks:)
