### ISSUE TITLE
App Store rejection due to NFC

### ISSUE THREAD

**Issue by rameshinnov** [Anyline/anyline-ocr-examples-ios#25]
We submitted our app for Apple review and it got rejected because the use of NFC tagging was unclear. Quote from review:
"Specifically, we need a demo video that shows a NFC feature with a designed hardware"

Here in our product integrated ANYLINE SDK for OCR feature, but in Anyline API it has NFC feature.

Please let us know how to resolve it.

Version info:
ANYLINE SDK version 35
Xcode: 12.1
Guideline 2.1 - Information Needed

**The below is the information sent from Apple** 

"We're looking forward to completing our review of your app. Before we can continue, we need a video that demonstrates the current version, 2109.06, in use on a physical iOS device, pairing and interacting with the designated hardware.

Specifically, we need a demo video that shows a NFC feature with a designed hardware.

Keep these requirements in mind as you make your demo video: 

- Only use footage of your app running on a physical iOS device, not on a simulator. 
- Make sure t_he video clearly documents all relevant app features, services, and user permission requests.
- You can use a screen recorder to capture footage of your app in use. 

Next Steps

Create the demo video, add a link to the video in the App Review Information section of your app’s page in App Store Connect, and reply to this message in App Store Connect.

To add the video link:

- Sign in to App Store Connect.
- Click on My Apps.
- Select your app.
- Click on the app version on the left side of the screen.
- Scroll down to App Review Information.
- Provide the demo video link and any necessary access details in the Notes section.
- Click the Save button at the top of the Version Information page.

Please note that if your app can only be reviewed with a demo video, you’ll need to provide an updated demo video for every app submission"

**Comment by aldrichanyline** [comment]
Hi, 

The Anyline framework does offer NFC functionality, but it can be disabled to avoid having to justify its use to the App Review board. If your application does not use any NFC features, I would suggest making some changes to your framework integration:

- Add `-weak_framework CoreNFC` to `OTHER_LDFLAGS` (also known as **Other Linker Flags**).

Rebuild and resubmit.

If you deem it fit to do so, please also include an appeal to the board along these lines: "our app does not have any Entitlement, or Profile, that would allow us to use NFC. The framework is weak-referenced by a third-party library".

Best of luck!

Regards,
Aldrich

**Comment by berndkamplanyline** [comment]
Thanks @aldrichanyline for responding. If your issue is solved with this answer, great, otherwise please raise a support request using the Anyline Helpdesk. See below how to do that. Thank you!

---
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!

**Comment by rameshinnov** [comment]
thanks @aldrichanyline issue got resolved. Thanks for quick response.
