### ISSUE TITLE
Positions of flash-alignment

### ISSUE THREAD

**Issue by Rikco** [Anyline/anyline-ocr-examples-ios#7]
Dear Anyline-Team,

the flash-alignment is not working. Top-Right e.g. looks like that with plugins for GermanIDFront and MRZ.

Device iPhone 6S Plus, iOS 12.2

Regards,
Enrico

![IMG_0994](https://user-images.githubusercontent.com/8440846/59596917-e7fe4280-90f8-11e9-9f2f-3dbb1486369e.PNG)
![IMG_0993](https://user-images.githubusercontent.com/8440846/59596925-edf42380-90f8-11e9-85f4-ca022772eede.PNG)

**Comment by melaniamuir** [comment]
Hi Enrico,

Sorry for the late response.

In the flash button configuration:

Here is the original line of code to set the location:
`scanView.flashButtonConfig?.flashAlignment = .bottomRight
`
Instead, please use this code:
`scanView.flashButtonConfig = ALFlashButtonConfig.init(flashMode: .manual, flashAlignment: .bottomRight, flashOffset: .zero)`

You may have to play a bit with the flashOffset, because the button may disappear off the screen when positioned at the very bottom:
`scanView.flashButtonConfig = ALFlashButtonConfig.init(flashMode: .manual, flashAlignment: .bottomRight, flashOffset: CGPoint(x: 0, y: -100))`

Please let us know if the issue persists to assist you further.

Thanks,
Melania

**Comment by philippAnyline** [comment]
Hi Enrico,

We had a small internal flash rework. Could you please try if this issue persists for you? 

Please open another issue if this is still an issue for you.

Thanks and regards,
Philipp
